version: 2

models:
  - name: stg_ai_responses
    description: "1 ligne = 1 réponse de l'IA pour une question, un modèle et un prompt"
    columns:
      - name: question_id
        tests:
          - not_null
      - name: model
        tests:
          - not_null
      - name: prompt_version
        tests:
          - not_null
      - name: correct_letter
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['A', 'B', 'C', 'D']
      - name: ai_letter
        tests:
          - accepted_values:
              arguments:
                values: ['A', 'B', 'C', 'D']
      - name: ai_correct
        tests:
          - not_null
      - name: is_valid_format
        tests:
          - not_null
