version: 2

sources:
  - name: silver_files
    tables:
      - name: questions_clean
        meta:
          external_location: "read_parquet('silver/questions_clean.parquet')"
      - name: ai_responses
        meta:
          external_location: "read_parquet('silver/ai_responses/*.parquet')"
